main/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage,name="home"),
    path('search/', views.user_homepage,name="search"),
    path('server_details/<slug:name>', views.server_details,name="server_details"),
    path('server_details/', views.server_details,name="server_details"),
    #path('login/', views.user_login,name="login"),
    path('login/', auth_views.LoginView.as_view(template_name='main/user_login.html'),name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/user_logout.html'),name="logout"),
    path('user_home', views.user_homepage,name="user_home"),
    path('logs/', views.view_logs,name="logs"),

]

password_safe/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Servers(models.Model):
    hostname = models.CharField(max_length=50, unique=True, primary_key=True)
    ip = models.CharField(max_length=15, unique=True)
    class Meta:
        verbose_name_plural ='Servers'
    def __str__(self):
        return self.hostname

class ServerDetails(models.Model):
    hostname =  models.ForeignKey(Servers, on_delete=models.CASCADE)
    password = models.CharField(max_length=50, default='hi')
    last_password = models.CharField(max_length=50, default='hi')
    last_password_modified = models.DateTimeField(default=timezone.now)

    #def __str__(self):
    #    return self.hostname

    class Meta:
        verbose_name_plural ='ServerDetails'

class Logs(models.Model):
    serv_name = models.CharField(max_length=50)
    user_accessed = models.CharField(max_length=50)
    time_of_access = models.DateTimeField(default=timezone.now)
    reason = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural ='ServerDetails'

main/forms.py
from django.contrib.auth.forms import AuthenticationForm

main/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from .models import Servers,ServerDetails,Logs


# Create your views here.

@login_required
def homepage(request):
    #return HttpResponse('<h1>hello</h1>')
    if request.user.is_superuser:
        return render(request,"main/home.html",{'serv':Servers.objects.all()})
    else:
        return redirect("main:user_home")


@login_required
def server_details(request,name):
    #return HttpResponse('<h1>hello</h1>')
    obj = get_object_or_404(ServerDetails.objects.all(), hostname=name)
    return render(request, "main/server_details.html", {'serv': obj})

@login_required
def user_homepage(request):
    if request.method == 'POST':
        form = request.POST
        log = Logs(serv_name = form['serv_inp'], user_accessed = request.user.username, reason= form['comment'])
        log.save()
        #obj = get_object_or_404(ServerDetails.objects.all(), hostname=form['serv_inp'])
        return redirect('server_details/'+form['serv_inp'])
    return render(request, "main/user_home.html")

@login_required
def view_logs(request):
    logs = Logs.objects.all()
    return render(request, "main/logs.html", {'logs': logs})


'''
def user_login(request):
    if request=='POST':
        form = AuthenticationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            #user =
            #login(user)
    form = AuthenticationForm()
    return render(request, "main/user_login.html", {'form': form})
'''

main/templates/main/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>

{% include "main/includes/navbar.html" %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


</body>

</html>

main/templates/main/home.html
{% extends "main/header.html" %}
{% block content %}
<span class="flow-text"> <h2 > List of Servers</h2> </span>
    <table class="highlight responsive-table"> <!--  centered highlight striped responsive-table -->

        <thead>
          <tr>
              <th>Server</th>
              <th>IP Address</th>
          </tr>
        </thead>

        <tbody>
        {% for s in serv  %}
          <tr>
              <td>{{s.hostname}}</td>
              <td><a href="/server_details/{{s.hostname}}">{{s.ip}}</a></td>
          </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}


<!-- my old code


    <table>
        {% for s in serv  %}
        <tr><td>{{s.hostname}}</td>  <td>{{s.ip}}</td></tr>
        {% endfor %}

    </table>
-->

main/templates/main/includes/footer.html
<footer class="page-footer">

        <div class="container" align = "bottom">
        © 2019 All Rights Reserved
        <!--<a class="grey-text text-lighten-4 right" href="#!">More Links</a>-->
        </div>

</footer>


<!--

          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>

-->

main/templates/main/includes/navbar.html
<nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo" >  P_BOX </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_superuser %}
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'main:user_home'%}">Search</a></li>
            {% else %}
                <li><a href="/">Home</a></li>
            {% endif %}
            {% if user.is_superuser %}
                <!-- <li><a href="/account">{{user.username|title}}</a></li> -->
                <li><a href="/logs">Logs</a></li>
            {% endif %}
            {% if user.is_authenticated %}
                <!-- <li><a href="/account">{{user.username|title}}</a></li> -->
                <li><a href="/logout">Logout</a></li>
            {% else %}
                <!-- <li><a href="/register">Register</a></li> -->
                <li><a href="/login">Login </a></li>
            {% endif %}

      </ul>
    </div>
 </nav>

main/templates/main/logs.html
{% extends "main/header.html" %}
{% block content %}
<span class="flow-text"> <h4 > Logs</h4> </span>
    <table class="highlight"> <!--  centered highlight striped responsive-table -->
        <thead>
          <tr>
              <th>User</th>
              <th>Server Accessesd</th>
              <th>Time</th>
              <th>Reason</th>
          </tr>
        </thead>

        <tbody>
        {% for log in logs  %}
          <tr>
              <!-- <td> {{log.user_accessed}} --  has accessed  ! {{log.serv_name}} ! on  -{{log.time_of_access}}-  for the Reason: {{log.reason}}</td> -->
              <td> {{log.user_accessed}} </td>
              <td>{{log.serv_name}}</td>
              <td>{{log.time_of_access}}</td>
              <td>{{log.reason}}</td>
          </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

main/templates/main/server_details.html
{% extends "main/header.html" %}

{% block content %}
<span class="flow-text"> <h3 > Server Details </h3> </span>

<table class="striped responsive-table"> <!--  centered highlight striped responsive-table -->

        <!-- <thead>
          <tr>
              <th>Server Details</th>
          </tr>
        </thead> -->

        <tbody>

          <tr>
              <td><b>Host Name : </b></td>
              <td>{{serv.hostname}}</td>
          </tr>
          <tr>
              <td><b>Password : </b></td>
              <td>{{serv.password}}</td>
          </tr>
          <tr>
              <td><b>Last Password : </b></td>
              <td>{{serv.last_password}}</td>
          </tr>
          <tr>
              <td><b>Password Modified Date : </b></td>
              <td>{{serv.last_password_modified}}</td>
          </tr>

        </tbody>

    </table>

{% endblock %}

main/templates/main/user_home.html
{% extends "main/header.html" %}
{% block content %}

<div class="">
    <h4 class="flow-text"> Welcome to the P_BOX , Please provide Server Hostname and Reason <h4>
    <form class=""  method="post">
        {% csrf_token %}

        <div class ="section">
            <label for="serv_inp" class="flow-text">Server Hostname:</label> <input type="text" name="serv_inp" value=""  required/>
        </div>
        <div class ="section">
            <label for="comment" class="flow-text">Reason:</label> <input type="text" name="comment" value="" required/>
        </div>
        <div class ="section">
            <button type="submit" name="button" class="btn waves-effect waves-light"> Search </button>
        </div>

    </form>

</div>
{% endblock content %}

main/templates/main/user_login.html
{% extends "main/header.html" %}
{% block content %}

   <div class="container">
        <br>
        <span class="flow-text"> Login to acces the Content</span>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn" type="submit"> Login </button>
        </form>
       <br>
        <p>Please contact your Administrator for Login details</p>
   </div>

{% endblock %}

main/templates/main/user_logout.html
{% extends "main/header.html" %}
{% block content %}

   <div class="container">
       <br>
        <h4> You have been Logged out </h4>
        <div class="divider"></div>
        <a href="{% url 'main:login' %}"> Log in Again</a>

   </div>

{% endblock %}